name: CI/CD React App to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    - name: Install Ansible
      run: sudo apt install -y ansible

    - name: Save EC2 private key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Run Ansible Playbook
      run: ansible-playbook deploy/deploy.yml -i deploy/inventory.ini
